### PR TITLE
feat: bump to use nodejs 20 runtime

### PR DESCRIPTION
**Pull request by chenrui333**
This is consistent with all the recent github action updates. (mostly in actions repos, like actions/checkout, actions/setup-node, etc.)

-------

Node12 was deleted from runner. Node20 was added to Actions Runner on v2.308.0.
Node16 has en end of life on 11 Sep 2023.

This PR updates the default runtime to node20, rather then node16

relates to https://github.com/actions/runner/pull/2732

-----

also need a major version bump per this PR merge

### CODE REVIEW

**Comment by chenrui333** [comment]
just vercel deployment issue

image

**Comment by vn7n24fzkq** [comment]
Hi, @chenrui333, Thanks for your excellent work.
Everything looks good

**Comment by chenrui333** [comment]
@vn7n24fzkq can you bump a major release instead of minor release.

**Comment by vn7n24fzkq** [comment]
@chenrui333 Yeah, I think we can do that.

**Pull request merged**
