### PR TITLE
feat: moonlight based theme

### PR DESCRIPTION
**Pull request by LucasAlexander13**

### CODE REVIEW

**Comment by LucasAlexander13** [comment]
Hi @vn7n24fzkq , how are you? I want to contribute to this awesome repo by adding my favorite theme. Can you help me to do so? I've already include de theme palette in theme.ts file, let me know if there are other requirements.

**Comment by vn7n24fzkq** [comment]
Awesome!

I had already deployed it on the [preview page](https://github-profile-summary-cards-dxcbm1x9r-vn7n24fzkq.vercel.app/demo.html).




Looks good!
Just in case, do you want to make any changes before we merge it?

**Comment by LucasAlexander13** [comment]
Looks perfect that way, lets merge!

**Comment by LucasAlexander13** [comment]
Done

**Comment by vn7n24fzkq** [comment]
@LucasAlexander13 Great!

https://github-profile-summary-cards-392tqnxp4-vn7n24fzkq.vercel.app/demo.html

Let's check it again.

**Comment by vn7n24fzkq** [comment]
@LucasAlexander13 Please let me know if we can merge it.

**Comment by LucasAlexander13** [comment]
@vn7n24fzkq perfect! lets merge

**Comment by vn7n24fzkq** [comment]
Thanks again!

**Pull request merged**
