### PR TITLE
Improve wording in summary cards

### LINKED ISSUE #17: [Feature request] Improve the Wording in Summary Cards
**Context**

The current wording used in the summary cards sounds a little unnatural. There are also a couple minor formatting annoyances, like using lower case where I feel upper case would be more appropriate.

**Alternatives**

An alternative is not available.

**Has the feature been requested before?**

No, it has not been requested before.

**If the feature request is approved, would you be willing to submit a PR?**

Yes.

### PR DESCRIPTION
**Pull request by Matteas-Eden**
See title.

I felt that some of the wording used in the cards was awkward, or that some added capitalisation in places could improve the way the cards look. Originally I was going to simply maintain a fork, but integrating that fork with GitHub actions became troublesome, so instead I'm (attempting to) contribute to the main repo.

I wasn't sure whether to open an issue or not. Let me know if there's a preference for PRs to have issues attached.

**UPDATE**
Closes #17

### CODE REVIEW

**Comment by vn7n24fzkq** [comment]
@Matteas-Eden Thanks for your contribution.
It would be good to have an issue , because any change will effect many users, an issue can get more people to participate in the discussion.

I'm not a native English speaker, so the grammar or used word in the cards might be odd, any PR about that I will be appreciated.

**Comment by vn7n24fzkq** [comment]
By the way, I would like to merge this PR if no one else disapproved it.

**Comment by Matteas-Eden** [comment]
@vn7n24fzkq I've created an issue for what this PR solves in an attempt to increase visibility and encourage discussion. The issue is #17.

**Comment by vn7n24fzkq** [comment]
Thanks!

**Pull request merged**
