### PR TITLE
feat: Added exclude argument for languages

### PR DESCRIPTION
**Pull request by MiranDaniel**
Added an optional `exclude` argument for excluding languages from the cards. Accepts comma separated lists (ex. `cpp,java`).

### CODE REVIEW

**Comment by vn7n24fzkq** [comment]
Awesome work!
I will review this tomorrow.

**Comment by vn7n24fzkq** [comment]
Do we need those modules in `package.json`?      
```
"serverless": "^3.20.0",
"vercel-node-server": "^2.2.1"
```
And if possible, I think we can change the `package-lock.json` just before release.
Everything else looks good to me.

**Comment by MiranDaniel** [comment]
My bad, didn't notice those 2 new modules, not needed.

**Comment by vn7n24fzkq** [comment]
Thanks! 
Also, `package-lock.json` should not be changed, can you revert that?

**Comment by vn7n24fzkq** [comment]
And there are some conflicts in `README.md`.
If it's not trouble for you could you please resolve that?

**Comment by vn7n24fzkq** [comment]
Thanks! @MiranDaniel 
Seems `package.json` got a parsing error, so `Tests` and `Lint` cannot pass.
I guess because there is an extra comma at the end of `"retry-axios": "^2.6.0", `

**Comment by vn7n24fzkq** [comment]
@MiranDaniel , Hi, do you still working on this?
If you are busy, I can help with the rest steps. I think we can merge this after solving the conflict.

**Comment by vn7n24fzkq** [comment]
Hi @MiranDaniel.

Are you still working on this? 
Since this PR is almost done, if you don't mind I can take over the rest part and keep your commit in the commit history.

**Pull request merged**
