### PR TITLE
new color themes

### PR DESCRIPTION
**Pull request by manojuppala**
New color themes :
- radical (https://github.com/vn7n24fzkq/github-profile-summary-cards/issues/66 )
- gruvbox
- tokyonight
- cobalt
- dark

### CODE REVIEW

**Comment by vn7n24fzkq** [comment]
Hi @manojuppala, thanks for your work, I was checking this PR.

 `radical`,`gruvbox` and `tokyonight` look good.
 
 For the `dark` theme, I'm not sure do we need another dark theme here, we already have a `github_dark` theme.

 And `cobalt` seems weird to me, can you show me what is those color codes based on?

**Comment by manojuppala** [comment]
> Hi @manojuppala, thanks for your work, I was checking this PR.
> 
> `radical`,`gruvbox` and `tokyonight` look good.
> 
> For the `dark` theme, I'm not sure do we need another dark theme here, we already have a `github_dark` theme.
> 
> And `cobalt` seems weird to me, can you show me what is those color codes based on?

ok i have removed dark and cobalt themes.

**Comment by vn7n24fzkq** [comment]
Thanks!

**Comment by vn7n24fzkq** [comment]
Closes #77

**Pull request merged**
