### PR TITLE
Fixed stroke opacity in new themes

### PR DESCRIPTION
**Pull request by george-gca**

### CODE REVIEW

**Comment by george-gca** [comment]
Fixing some themes introduced in #135

**Comment by george-gca** [comment]
@vn7n24fzkq I tried to create my own vercel app, but to no avail. How can I create my own vercel app based on yours?

**Comment by vn7n24fzkq** [comment]
Sorry for the late reply.

I will check about the Vercel creation.

And thanks for the contribution.

**Comment by george-gca** [comment]
@vn7n24fzkq can you add the screenshots of the new themes? And also on the vercel app? You probably know the best way to do this.
The new themes are:

```
algolia
apprentice
aura_dark
aura
ayu_mirage
bear
blue_green
blueberry
buefy
calm
chartreuse_dark
city_lights
cobalt
cobalt2
codeSTACKr
darcula
dark
date_night
discord_old_blurple
flag_india
gotham
graywhite
great_gatsby
highcontrast
jolly
kacho_ga
maroongold
material_palenight
merko
midnight_purple
moltack
moonlight
nightowl
noctis_minimus
ocean_dark
omni
onedark
outrun
panda
prussian
react
rose_pine
shades_of_purple
slateorange
swift
synthwave
vision_friendly_dark
yeblu
```

**Comment by vn7n24fzkq** [comment]
Hey @george-gca , I just create my own one, what problem you faced when creating on Vercel?
I think we should create another issue for this problem.

**Comment by vn7n24fzkq** [comment]
> @vn7n24fzkq can you add the screenshots of the new themes? And also on the vercel app? You probably know the best way to do this. The new themes are:
> 
> ```
> algolia
> apprentice
> aura_dark
> aura
> ayu_mirage
> bear
> blue_green
> blueberry
> buefy
> calm
> chartreuse_dark
> city_lights
> cobalt
> cobalt2
> codeSTACKr
> darcula
> dark
> date_night
> discord_old_blurple
> flag_india
> gotham
> graywhite
> great_gatsby
> highcontrast
> jolly
> kacho_ga
> maroongold
> material_palenight
> merko
> midnight_purple
> moltack
> moonlight
> nightowl
> noctis_minimus
> ocean_dark
> omni
> onedark
> outrun
> panda
> prussian
> react
> rose_pine
> shades_of_purple
> slateorange
> swift
> synthwave
> vision_friendly_dark
> yeblu
> ```

Sure, but I don't where are those themes from.
Same as the previous reply, we can create another issue for this.

**Pull request merged**
